#!/usr/bin/python

import sys
sys.path.append('Libraries/NUKit/Tools')
import nukit

if __name__ == "__main__":

    additional_themes = [{"name": "NUFlat",
                          "short_arg": "n"}]

    nukit.perform_build(additional_libraries=[], additional_themes=additional_themes)
