/*
*   Filename:         Jakefile
*   Created:          Wed Apr 22 19:07:16 PDT 2015
*   Author:           Antoine Mercadal <antoine.mercadal@alcatel-lucent.com>
*   Description:      VSA
*   Project:          VSD - Nuage - Data Center Service Delivery - IPD
*
* Copyright (c) 2011-2012 Alcatel, Alcatel-Lucent, Inc. All Rights Reserved.
*
* This source code contains confidential information which is proprietary to Alcatel.
* No part of its contents may be used, copied, disclosed or conveyed to any party
* in any manner whatsoever without prior written permission from Alcatel.
*
* Alcatel-Lucent is a trademark of Alcatel-Lucent, Inc.
*
*/

require("./Libraries/NUKit/Tools/config.jake");

BUILD_INFO["PROJECT_NAME"]       = "SpecificationsDirector";
BUILD_INFO["PROJECT_IDENTIFIER"] = "";
BUILD_INFO["PROJECT_VERSION"]    = "";
BUILD_INFO["PROJECT_AUTHOR"]     = "Nuage Networks";
BUILD_INFO["PROJECT_CONTACT"]    = "antoine@nuagenetworks.net";
BUILD_INFO["PROJECT_SOURCES"]    = new FILELIST("*.j", "Associators/**/*.j", "DataViews/**/*.j", "Models/**/*.j", "Transformers/*.j", "ViewControllers/**/*.j")
BUILD_INFO["PROJECT_FRAMEWORKS"] = ["TNKit", "NUKit", "Bambou"];
BUILD_INFO["PROJECT_TYPE"]       = "APPLICATION";

require("./Libraries/NUKit/Tools/common.jake");

TASK ("deploy", ["predeploy"]);
