{
    "apis": {
        "children": {},
        "parents": {
            "/specifications/{id}/[__RESOURCE_NAME__]": {
                "RESTName": "specification",
                "resourceName": "specifications",
                "entityName": "Specification",
                "operations": [
                    {
                        "availability": null,
                        "method": "GET"
                    },
                    {
                        "availability": null,
                        "method": "POST"
                    }
                ]
            },
            "/abstracts/{id}/[__RESOURCE_NAME__]": {
                "RESTName": "abstract",
                "resourceName": "abstracts",
                "entityName": "Abstract",
                "operations": [
                    {
                        "availability": null,
                        "method": "GET"
                    },
                    {
                        "availability": null,
                        "method": "POST"
                    }
                ]
            }
        },
        "self": {
            "/[__RESOURCE_NAME__]/{id}": {
                "RESTName": "[__REST_NAME__]",
                "resourceName": "[__RESOURCE_NAME__]",
                "entityName": "[__ENTITY_NAME__]",
                "operations": [
                    {
                        "availability": null,
                        "method": "PUT"
                    },
                    {
                        "availability": null,
                        "method": "DELETE"
                    },
                    {
                        "availability": null,
                        "method": "GET"
                    }
                ]
            }
        }
    },
    "model": {

        "package": "specifications",

        "attributes": {
            "path": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": false,
                "description": "The path",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": false,
                "transient": false,
                "type": "string",
                "unique": false
            },
            "deprecated": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": false,
                "description": "Defines if the api is deprecated",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": false,
                "transient": false,
                "type": "boolean",
                "unique": false
            },
            "relationship": {
                "allowedChars": null,
                "allowedChoices": ["child", "member"],
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": false,
                "description": "Defines if the api is deprecated",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": false,
                "transient": false,
                "type": "enum",
                "unique": false
            },
            "allowsGet": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": false,
                "description": "Defines if teh available operations",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": false,
                "transient": false,
                "type": "bool",
                "unique": false
            },
            "allowsCreate": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": false,
                "description": "Defines if teh available operations",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": false,
                "transient": false,
                "type": "bool",
                "unique": false
            },
            "allowsUpdate": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": false,
                "description": "Defines if teh available operations",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": false,
                "transient": false,
                "type": "bool",
                "unique": false
            },
            "allowsDelete": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": false,
                "description": "Defines if teh available operations",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": false,
                "transient": false,
                "type": "bool",
                "unique": false
            },
            "associatedSpecificationID": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": null,
                "description": "the associated specification.",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": false,
                "readOnly": false,
                "required": true,
                "transient": false,
                "type": "string",
                "unique": true
            }
        }
    }
}