{
    "model": {
        "attributes": {
            "issues": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": false,
                "description": "The eventual parsing issues",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": false,
                "transient": false,
                "type": "list",
                "unique": false
            }
        }
    }
}