{
    "attributes": {
        "issues": {
            "allowed_chars": null,
            "allowed_choices": null,
            "autogenerated": false,
            "availability": null,
            "channel": null,
            "creation_only": false,
            "default_order": false,
            "default_value": false,
            "description": "The eventual parsing issues",
            "exposed": true,
            "filterable": true,
            "format": null,
            "max_length": null,
            "max_value": null,
            "min_length": null,
            "min_value": null,
            "orderable": true,
            "read_only": false,
            "required": false,
            "transient": false,
            "type": "list",
            "unique": false
        }
    }
}