{
    "apis": {
        "children": {},
        "parents": {
            "/repositories/{id}/apiinfos": {
                "RESTName": "repository",
                "resourceName": "repositories",
                "entityName": "Repository",
                "operations": [
                    {
                        "availability": null,
                        "method": "GET"
                    },
                    {
                        "availability": null,
                        "method": "POST"
                    }
                ]
            }
        },
        "self": {
            "/apiinfos/{id}": {
                "RESTName": "apiinfo",
                "resourceName": "apiinfos",
                "entityName": "APIInfo",
                "operations": [
                    {
                        "availability": null,
                        "method": "PUT"
                    },
                    {
                        "availability": null,
                        "method": "DELETE"
                    },
                    {
                        "availability": null,
                        "method": "GET"
                    }
                ]
            }
        }
    },
    "model": {
        "RESTName": "apiinfo",
        "resourceName": "apiinfos",
        "entityName": "APIInfo",
        "description": "Represents information about the entire specifications.",
        "extends": ["@parsable"],
        "package": "specifications",

        "attributes": {
            "version": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": null,
                "description": "The version of the api",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": true,
                "transient": false,
                "type": "string",
                "unique": true
            },
            "prefix": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": false,
                "description": "The prefix of the entire api.",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": false,
                "readOnly": false,
                "required": true,
                "transient": false,
                "type": "string",
                "unique": true
            },
            "root": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": false,
                "description": "The object in the specification to consider as the root object.",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": false,
                "readOnly": false,
                "required": true,
                "transient": false,
                "type": "string",
                "unique": true
            }
        }
    }
}