{
    "apis": {
        "children": {
            "/abstracts/{id}/models": {
                "RESTName": "model",
                "resourceName": "models",
                "entityName": "Model",
                "operations": [
                    {
                        "availability": null,
                        "method": "GET"
                    }
                ]
            },
            "/abstracts/{id}/attributes": {
                "RESTName": "attribute",
                "resourceName": "attributes",
                "entityName": "Attribute",
                "operations": [
                    {
                        "availability": null,
                        "method": "GET"
                    },
                    {
                        "availability": null,
                        "method": "POST"
                    }
                ]
            },
            "/abstracts/{id}/childapis": {
                "RESTName": "childapi",
                "resourceName": "childapis",
                "entityName": "ChildAPI",
                "operations": [
                    {
                        "availability": null,
                        "method": "GET"
                    },
                    {
                        "availability": null,
                        "method": "POST"
                    }
                ]
            },
            "/abstracts/{id}/parentapis": {
                "RESTName": "parentapi",
                "resourceName": "parentapis",
                "entityName": "ParentAPI",
                "operations": [
                    {
                        "availability": null,
                        "method": "GET"
                    },
                    {
                        "availability": null,
                        "method": "POST"
                    }
                ]
            }
        },
        "parents": {
            "/repositories/{id}/abstracts": {
                "RESTName": "repository",
                "resourceName": "repositories",
                "entityName": "Repository",
                "operations": [
                    {
                        "availability": null,
                        "method": "GET"
                    },
                    {
                        "availability": null,
                        "method": "POST"
                    }
                ]
            }
        },
        "self": {
            "/abstracts/{id}": {
                "RESTName": "abstract",
                "resourceName": "abstracts",
                "entityName": "Abstract",
                "operations": [
                    {
                        "availability": null,
                        "method": "PUT"
                    },
                    {
                        "availability": null,
                        "method": "DELETE"
                    },
                    {
                        "availability": null,
                        "method": "GET"
                    }
                ]
            }
        }
    },
    "model": {
        "RESTName": "abstract",
        "resourceName": "abstracts",
        "entityName": "Abstract",
        "description": "Represents the abstract of an object.",
        "extends": [],
        "package": "specifications",

        "attributes": {
            "name": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": null,
                "description": "The name of the abstract. example 'unicorn'",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": true,
                "transient": false,
                "type": "string",
                "unique": true
            }
        }
    }
}