{
    "apis": {
        "children": {
            "/models/{id}/abstracts": {
                "RESTName": "abstract",
                "resourceName": "abstracts",
                "entityName": "Abstract",
                "relationship": "member",
                "operations": [
                    {
                        "availability": null,
                        "method": "GET"
                    },
                    {
                        "availability": null,
                        "method": "PUT"
                    }
                ]
            }
        },
        "parents": {
            "/specifications/{id}/models": {
                "RESTName": "specification",
                "resourceName": "specifications",
                "entityName": "Specification",
                "operations": [
                    {
                        "availability": null,
                        "method": "GET"
                    }
                ]
            },
            "/abstacts/{id}/models": {
                "RESTName": "abstact",
                "resourceName": "abstacts",
                "entityName": "Abstact",
                "operations": [
                    {
                        "availability": null,
                        "method": "GET"
                    }
                ]
            }
        },
        "self": {
            "/models/{id}": {
                "RESTName": "model",
                "resourceName": "models",
                "entityName": "Model",
                "operations": [
                    {
                        "availability": null,
                        "method": "PUT"
                    }
                ]
            }
        }
    },
    "model": {
        "RESTName": "model",
        "resourceName": "models",
        "entityName": "Model",
        "description": "Represents the model",
        "extends": [],
        "package": "specifications",
        "attributes": {
            "description": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": null,
                "description": "The description of the specification. example 'unicorn is some kind of horse'",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": false,
                "transient": false,
                "type": "string",
                "unique": true
            },
            "package": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": null,
                "description": "The package of the specification",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": false,
                "transient": false,
                "type": "string",
                "unique": true
            },
            "objectRESTName": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": null,
                "description": "The rest name of the object. example 'unicorn'",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": false,
                "transient": false,
                "type": "string",
                "unique": true
            },
            "objectResourceName": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": null,
                "description": "The resource name of the object. example 'unicorns'",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": false,
                "readOnly": false,
                "required": false,
                "transient": false,
                "type": "string",
                "unique": true
            },
            "entityName": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": null,
                "description": "The entoty name of the object. example 'Unicorn'.",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": false,
                "readOnly": false,
                "required": false,
                "transient": false,
                "type": "string",
                "unique": true
            },
            "extends": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": [],
                "description": "The other specifications this class extends",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": false,
                "readOnly": false,
                "required": false,
                "transient": false,
                "type": "list",
                "unique": true
            },
            "allowsGet": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": false,
                "description": "Defines if teh available operations",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": false,
                "transient": false,
                "type": "bool",
                "unique": false
            },
            "allowsUpdate": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": false,
                "description": "Defines if teh available operations",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": false,
                "transient": false,
                "type": "bool",
                "unique": false
            },
            "allowsDelete": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": false,
                "description": "Defines if teh available operations",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": false,
                "transient": false,
                "type": "bool",
                "unique": false
            }
        }
    }
}