{
    "rest_name": "specification",
    "resource_name": "specifications",
    "entity_name": "Specification",
    "description": "Represents the specification of an object.",
    "extends": ["@parsable", "@specification"],

    "attributes": {
        "root": {
            "allowed_chars": null,
            "allowed_choices": null,
            "autogenerated": false,
            "availability": null,
            "channel": null,
            "creation_only": false,
            "default_order": false,
            "default_value": null,
            "description": "true if root api",
            "exposed": true,
            "filterable": true,
            "format": null,
            "max_length": null,
            "max_value": null,
            "min_length": null,
            "min_value": null,
            "orderable": true,
            "read_only": false,
            "required": false,
            "transient": false,
            "type": "boolean",
            "unique": false
        }
    }
}